##############################################
#            Server Configuration            #
##############################################
server:
  port: 3000
  error:
    include-message: always

##############################################
#           Database Configuration           #
##############################################
spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: create